# .github/workflows/cache-dependencies.yml

name: 'Test Dependency Caching'

on: push

jobs:
  dependency-caching-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
          cache-dependency-path: 'package-lock.json'
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
