# .github/workflows/cache-dependencies.yml

name: 'Test Dependency Caching'

on: push

jobs:
  dependency-caching-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 👈 Required to retrieve git history

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache Node Module Dependencies
      uses: actions/cache@v2
      id: cache
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
